FORMAT: 1A

# Wanderlust
An API that maps smart phones to country based mobile phone providers

# Group Countries
The list of countries that have mobile phone carriers

## Countries Collection [/countries]
### List all Countries[GET]
+ Response 200 (application/json)

        {"data":[
            {
                "id": 1,
                "name": "United States",
                "abbr": "USA"
            },
            {
                "id": 2,
                "name": "China",
                "abbr": "CN"
            }
        ]}


### Create a Country [POST]
+ Request (application/json)

        { "name": "Japan", "abbr": "JPN" }

+ Response 201 (application/json)

        {"data":{ "id": 3, "name": "Japan", "abbr": "JPN"}}

## Country [/countries/{id}]
A single Country object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Country to perform action with. Has example value.

### Retrieve a Country [GET]
+ Response 200 (application/json)

    + Body

            { "id": 2, "name": "China", "abbr": "CN" }
            
### Remove a Country [DELETE]
+ Response 204


# Group Phones 
The list of phones that are generally considered "smart"

## Phones Collection [/phones]
### List all Phones[GET]
+ Response 200 (application/json)

        {"data":[
            {
                "id": 1,
                "name": "Nexus 4", 
                "manfacturer": "Motorola",
                "gsmType": ["GSM", "GPRS", "EDGE"],
                "gsmFreq": [850, 900, 1800, 1900], 
                "hspaType": ["UMTS / WCDMA","HSDPA", "HSUPA"], 
                "hSPAFreq": [1700, 1900, 2100],
                "lteType":  ["TD-LTE"]
            },
            {
                "id": 2, 
                "name": "HTC One",
                "manufacturer": "HTC",
                "gsmType": ["GSM", "GPRS", "EDGE"], 
                "gsmFreq": [850, 900, 1800, 1900], 
                "hspaType": ["UMTS / WCDMA", "HSPDA", "HSUPA"], 
                "hSPAFreq": [850, 900, 1900, 2100],
                "lteType": [] 
            }
        ]}


### Create a Phone [POST]
+ Request (application/json)

        {
            "name": "iPhone 5", 
            "manufacturer": "Apple",
            "gsmType": ["GSM", "GPRS", "EDGE"],
            "gsmFreq": [850, 900, 1800, 1900], 
            "hspaType": ["UMTS / WCDMA","HSDPA", "HSUPA"], 
            "hSPAFreq": [1700, 1900, 2100],
            "lteType":  ["TD-LTE"]
        }
        
+ Response 201 (application/json)

        {"data":{
            "id": 3,
            "name": "iPhone 5", 
            "manufacturer": "Apple",
            "gsmType": ["GSM", "GPRS", "EDGE"],
            "gsmFreq": [850, 900, 1800, 1900], 
            "hspaType": ["UMTS / WCDMA","HSDPA", "HSUPA"], 
            "hSPAFreq": [1700, 1900, 2100],
            "lteType":  ["TD-LTE"]
        }}

## Phones [/phones/{id}]
A single Phone object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Phone to perform action with. Has example value.

### Retrieve a Phone [GET]
+ Response 200 (application/json)

    + Body

            {"data":{
                "id": 2, 
                "name": "HTC One",
                "manufacturer": "HTC",
                "gsmType": ["GSM", "GPRS", "EDGE"], 
                "gsmFreq": [850, 900, 1800, 1900], 
                "hspaType": ["UMTS / WCDMA", "HSPDA", "HSUPA"], 
                "hSPAFreq": [850, 900, 1900, 2100],
                "lteType": [] 
            }}
            
### Remove a Phone [DELETE]
+ Response 204

# Group Networks 
The list of phone networks that are in countries

## Networks Collection [/networks]
### List all Networks [GET]
+ Response 200 (application/json)

        {"data":[
            {
                "id": 1,
                "name": "China Unicom",
                "countryID": 1,
                "gsmType": ["GSM", "GPRS", "EDGE"], 
                "gsmFreq": [850, 900, 1800, 1900], 
                "hspaType": ["UMTS / WCDMA", "HSDPA", "HSUPA"], 
                "HSPAFreq": [2100]
              },
            {
                "id": 2,
                "name": "ATT&T",
                "countryID": 1,
                "gsmType": ["GSM", "GPRS", "EDGE"], 
                "gsmFreq": [850, 1900], 
                "hspaType": ["UMTS / WCDMA", "HSDPA", "HSUPA"], 
                "HSPAFreq": [1700, 1900, 2100]
            },
            {
                "id": 3,
                "name": "T-Mobile",
                "countryID": 2,
                "gsmType":["GSM", "GPRS", "EDGE"], 
                "gsmFreq":[850, 1900], 
                "hspaType":["UMTS / WCDMA", "HSDPA", "HSUPA"], 
                "HSPAFreq":[1700, 2100]
            }
        ]}

### Create a Network [POST]
+ Request (application/json)

        {
            "name": "Verizon",
            "countryID": 1,
            "gsmType":["GSM", "GPRS", "EDGE"], 
            "gsmFreq":[850, 1900], 
            "hspaType":["UMTS / WCDMA", "HSDPA", "HSUPA"], 
            "HSPAFreq":[1700, 2100]
        }
        
+ Response 201 (application/json)

        {"data":{
            "id": 4,
            "name": "Verizon",
            "countryID": 1,
            "gsmType":["GSM", "GPRS", "EDGE"], 
            "gsmFreq":[850, 1900], 
            "hspaType":["UMTS / WCDMA", "HSDPA", "HSUPA"], 
            "HSPAFreq":[1700, 2100]
        }}

## Network [/networks/{id}]
A single Network object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Network to perform action with. Has example value.

### Retrieve a Network [GET]
+ Response 200 (application/json)

    + Body

            {"data":{
                "id": 3,
                "name": "T-Mobile",
                "countryID": 2,
                "gsmType":["GSM", "GPRS", "EDGE"], 
                "gsmFreq":[850, 1900], 
                "hspaType":["UMTS / WCDMA", "HSDPA", "HSUPA"], 
                "HSPAFreq":[1700, 2100]
            }}
            
### Remove a Network [DELETE]
+ Response 204

# Group Reports  
Return the reports on phones and networks

## Reports [/reports?phone={phone_id}&country={country_id}]

+ Parameters
    + phone_id (number, `123`, required) - ID of the phone.
    + country_id (number, `321`, required) - ID of the country.
    
### Return compatible networks [GET]
+ Response 200 (application/json)

        {"data":[
           {
                "provider": "AT&T",
                "voice_2g_data": "Yes",
                "data_3g": "Yes",
                "data_lte": "Yes"
           },
           {
               "provider": "US Cellular",
               "voice_2g_data": "Yes",
               "data_3g": "No",
               "data_lte": "Yes"
           },
           {
               "provider": "Verizon",
               "voice_2g_data": "No",
               "data_3g": "No",
               "data_lte": "No"
           },
           {
               "provider": "T-Mobile",
               "voice_2g_data": "Yes",
               "data_3g": "No",
               "data_lte": "No"
            }
        ]}
